backend:
  name: github
  repo: hyundaibinhduongvn/hyundaibinhduongvn.github.io
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Bài viết"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Nội dung", name: "body", widget: "markdown" }

